name: Build & test

on: [ push ]

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build heatshrink
        run: make

      - name: Test heatshrink static
        run: ./test_heatshrink_static

      - name: Test heatshrink dynamic
        run: ./test_heatshrink_dynamic
