name: Documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install Doxygen dependencies
        run: |
          sudo apt install -y doxygen graphviz
      - name: Install dependencies
        run: |
          pip install sphinx breathe sphinx_rtd_theme myst_parser
      - name: Run doxygen
        run: |
          doxygen Doxyfile
      - name: Sphinx build
        run: |
          sphinx-build doc/source build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/zephyr' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          force_orphan: true